# Generated by Django 5.2.12 on 2026-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
